# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ImageProcessing_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_image_processing(object):
    def setupUi(self, form_image_processing):
        form_image_processing.setObjectName("form_image_processing")
        form_image_processing.resize(1087, 695)
        form_image_processing.setStyleSheet("QWidget{\n"
"font-size: 18px;\n"
"background-color: rgb(150, 150, 150);\n"
"}\n"
"QComboBox{\n"
"background-color:rgb(50,50,50);\n"
"color:rgb(200,200,200)\n"
"}\n"
"QTreeView{\n"
"background-color:rgb(50,50,50);\n"
"border:1px solid rgb(25,25,25);\n"
"color:rgb(200,200,200)\n"
"}\n"
"QListView{\n"
"background-color:rgb(50,50,50);\n"
"border:1px solid rgb(25,25,25);\n"
"color:rgb(200,200,200)\n"
"}\n"
"QLineEdit{\n"
"color:rgb(200,200,200);\n"
"border:1px solid rgb(120,120,120);\n"
"background:rgb(50,50,50);\n"
"}\n"
"QPushButton {\n"
"  padding: 0px 8px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  color: rgb(220,220,220);\n"
"  background-color: rgb(0,125,210);\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color:  rgb(0,172,142);}\n"
"\n"
"QPushButton:hover:pressed {\n"
"  background-color: rgb(30,152,122);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border:0px solid;\n"
"    background: rgb(50,50,50);\n"
"    width: 30px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border:0px solid;\n"
"    background: rgb(50,50,50);\n"
"    height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(80,80,80);\n"
"    width:10px;\n"
"    margin:10px;\n"
"    border-radius:5px;\n"
"    min-height:30px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(80,80,80);\n"
"    height:10px;\n"
"    margin:10px;\n"
"    border-radius:5px;\n"
"    min-width:30px;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page{\n"
"background:none;\n"
"}\n"
"QScrollBar::add-page:vertical{\n"
"width:0px;\n"
"}\n"
"QScrollBar::sub-page:vertical{\n"
"width:0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"width: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"width: 0px;\n"
"}\n"
"QScrollBar::add-page:horizontal{\n"
"height:0px;\n"
"}\n"
"QScrollBar::sub-page:horizontal{\n"
"height:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"height: 0px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"height: 0px;\n"
"}\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    width:0px;\n"
" }\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    height:0px;\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(form_image_processing)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cb_cvt_color = QtWidgets.QCheckBox(form_image_processing)
        self.cb_cvt_color.setObjectName("cb_cvt_color")
        self.verticalLayout_5.addWidget(self.cb_cvt_color)
        self.frame_cvt_color = QtWidgets.QFrame(form_image_processing)
        self.frame_cvt_color.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_cvt_color.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cvt_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cvt_color.setObjectName("frame_cvt_color")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_cvt_color)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rb_gray = QtWidgets.QRadioButton(self.frame_cvt_color)
        self.rb_gray.setChecked(True)
        self.rb_gray.setObjectName("rb_gray")
        self.verticalLayout_7.addWidget(self.rb_gray)
        self.rb_color = QtWidgets.QRadioButton(self.frame_cvt_color)
        self.rb_color.setObjectName("rb_color")
        self.verticalLayout_7.addWidget(self.rb_color)
        self.verticalLayout_5.addWidget(self.frame_cvt_color)
        self.verticalLayout_12.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cb_resize = QtWidgets.QCheckBox(form_image_processing)
        self.cb_resize.setObjectName("cb_resize")
        self.verticalLayout_2.addWidget(self.cb_resize)
        self.frame_resize = QtWidgets.QFrame(form_image_processing)
        self.frame_resize.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_resize.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_resize.setObjectName("frame_resize")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_resize)
        self.gridLayout.setObjectName("gridLayout")
        self.le_height = QtWidgets.QLineEdit(self.frame_resize)
        self.le_height.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_height.setObjectName("le_height")
        self.gridLayout.addWidget(self.le_height, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_resize)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_resize)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.le_width = QtWidgets.QLineEdit(self.frame_resize)
        self.le_width.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_width.setObjectName("le_width")
        self.gridLayout.addWidget(self.le_width, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_resize)
        self.verticalLayout_12.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.cb_filters = QtWidgets.QCheckBox(form_image_processing)
        self.cb_filters.setObjectName("cb_filters")
        self.verticalLayout_6.addWidget(self.cb_filters)
        self.frame_filters = QtWidgets.QFrame(form_image_processing)
        self.frame_filters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_filters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_filters.setObjectName("frame_filters")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_filters)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cb_mean = QtWidgets.QCheckBox(self.frame_filters)
        self.cb_mean.setObjectName("cb_mean")
        self.verticalLayout.addWidget(self.cb_mean)
        self.cb_gaussian = QtWidgets.QCheckBox(self.frame_filters)
        self.cb_gaussian.setObjectName("cb_gaussian")
        self.verticalLayout.addWidget(self.cb_gaussian)
        self.cb_median = QtWidgets.QCheckBox(self.frame_filters)
        self.cb_median.setObjectName("cb_median")
        self.verticalLayout.addWidget(self.cb_median)
        self.cb_bilateral = QtWidgets.QCheckBox(self.frame_filters)
        self.cb_bilateral.setObjectName("cb_bilateral")
        self.verticalLayout.addWidget(self.cb_bilateral)
        self.cb_averaging = QtWidgets.QCheckBox(self.frame_filters)
        self.cb_averaging.setObjectName("cb_averaging")
        self.verticalLayout.addWidget(self.cb_averaging)
        self.verticalLayout_6.addWidget(self.frame_filters)
        self.verticalLayout_12.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_12)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cb_edges = QtWidgets.QCheckBox(form_image_processing)
        self.cb_edges.setEnabled(True)
        self.cb_edges.setObjectName("cb_edges")
        self.verticalLayout_10.addWidget(self.cb_edges)
        self.frame_edges = QtWidgets.QFrame(form_image_processing)
        self.frame_edges.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_edges.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_edges.setObjectName("frame_edges")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_edges)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.rb_canny = QtWidgets.QRadioButton(self.frame_edges)
        self.rb_canny.setChecked(True)
        self.rb_canny.setObjectName("rb_canny")
        self.verticalLayout_9.addWidget(self.rb_canny)
        self.rb_sobel = QtWidgets.QRadioButton(self.frame_edges)
        self.rb_sobel.setObjectName("rb_sobel")
        self.verticalLayout_9.addWidget(self.rb_sobel)
        self.rb_prewitt = QtWidgets.QRadioButton(self.frame_edges)
        self.rb_prewitt.setObjectName("rb_prewitt")
        self.verticalLayout_9.addWidget(self.rb_prewitt)
        self.rb_laplace = QtWidgets.QRadioButton(self.frame_edges)
        self.rb_laplace.setObjectName("rb_laplace")
        self.verticalLayout_9.addWidget(self.rb_laplace)
        self.verticalLayout_10.addWidget(self.frame_edges)
        self.verticalLayout_8.addLayout(self.verticalLayout_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.cb_thresholding = QtWidgets.QCheckBox(form_image_processing)
        self.cb_thresholding.setEnabled(True)
        self.cb_thresholding.setObjectName("cb_thresholding")
        self.verticalLayout_14.addWidget(self.cb_thresholding)
        self.frame_thresholding = QtWidgets.QFrame(form_image_processing)
        self.frame_thresholding.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_thresholding.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_thresholding.setObjectName("frame_thresholding")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_thresholding)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.rb_simple = QtWidgets.QRadioButton(self.frame_thresholding)
        self.rb_simple.setChecked(True)
        self.rb_simple.setObjectName("rb_simple")
        self.verticalLayout_13.addWidget(self.rb_simple)
        self.rb_adaptive = QtWidgets.QRadioButton(self.frame_thresholding)
        self.rb_adaptive.setObjectName("rb_adaptive")
        self.verticalLayout_13.addWidget(self.rb_adaptive)
        self.rb_otsu = QtWidgets.QRadioButton(self.frame_thresholding)
        self.rb_otsu.setObjectName("rb_otsu")
        self.verticalLayout_13.addWidget(self.rb_otsu)
        self.verticalLayout_14.addWidget(self.frame_thresholding)
        self.verticalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.cb_transformation = QtWidgets.QCheckBox(form_image_processing)
        self.cb_transformation.setObjectName("cb_transformation")
        self.verticalLayout_16.addWidget(self.cb_transformation)
        self.frame_transformation = QtWidgets.QFrame(form_image_processing)
        self.frame_transformation.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_transformation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_transformation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_transformation.setObjectName("frame_transformation")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_transformation)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 13, 1, 1)
        self.cb_translation = QtWidgets.QCheckBox(self.frame_transformation)
        self.cb_translation.setObjectName("cb_translation")
        self.gridLayout_4.addWidget(self.cb_translation, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 4, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 12, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 0, 7, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem6, 0, 9, 1, 1)
        self.le_translation_posY = QtWidgets.QLineEdit(self.frame_transformation)
        self.le_translation_posY.setMaximumSize(QtCore.QSize(30, 16777215))
        self.le_translation_posY.setObjectName("le_translation_posY")
        self.gridLayout_4.addWidget(self.le_translation_posY, 0, 6, 1, 1)
        self.le_rotation_angle = QtWidgets.QLineEdit(self.frame_transformation)
        self.le_rotation_angle.setMaximumSize(QtCore.QSize(30, 16777215))
        self.le_rotation_angle.setObjectName("le_rotation_angle")
        self.gridLayout_4.addWidget(self.le_rotation_angle, 1, 3, 1, 1)
        self.lbl_posY = QtWidgets.QLabel(self.frame_transformation)
        self.lbl_posY.setEnabled(False)
        self.lbl_posY.setObjectName("lbl_posY")
        self.gridLayout_4.addWidget(self.lbl_posY, 0, 5, 1, 1)
        self.cb_perspective = QtWidgets.QCheckBox(self.frame_transformation)
        self.cb_perspective.setObjectName("cb_perspective")
        self.gridLayout_4.addWidget(self.cb_perspective, 2, 0, 1, 1)
        self.le_translation_posX = QtWidgets.QLineEdit(self.frame_transformation)
        self.le_translation_posX.setMaximumSize(QtCore.QSize(30, 16777215))
        self.le_translation_posX.setObjectName("le_translation_posX")
        self.gridLayout_4.addWidget(self.le_translation_posX, 0, 3, 1, 2)
        self.lbl_angle = QtWidgets.QLabel(self.frame_transformation)
        self.lbl_angle.setEnabled(False)
        self.lbl_angle.setObjectName("lbl_angle")
        self.gridLayout_4.addWidget(self.lbl_angle, 1, 1, 1, 2)
        self.cb_rotation = QtWidgets.QCheckBox(self.frame_transformation)
        self.cb_rotation.setObjectName("cb_rotation")
        self.gridLayout_4.addWidget(self.cb_rotation, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 8, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 0, 11, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 10, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 0, 14, 1, 1)
        self.lbl_posX = QtWidgets.QLabel(self.frame_transformation)
        self.lbl_posX.setEnabled(False)
        self.lbl_posX.setObjectName("lbl_posX")
        self.gridLayout_4.addWidget(self.lbl_posX, 0, 1, 1, 1)
        self.verticalLayout_16.addWidget(self.frame_transformation)
        self.verticalLayout_4.addLayout(self.verticalLayout_16)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.frame_5 = QtWidgets.QFrame(form_image_processing)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_image_path = QtWidgets.QLabel(self.frame_5)
        self.lbl_image_path.setEnabled(True)
        self.lbl_image_path.setObjectName("lbl_image_path")
        self.horizontalLayout_3.addWidget(self.lbl_image_path)
        self.le_file_path = QtWidgets.QLineEdit(self.frame_5)
        self.le_file_path.setObjectName("le_file_path")
        self.horizontalLayout_3.addWidget(self.le_file_path)
        self.btn_browse = QtWidgets.QPushButton(self.frame_5)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout_3.addWidget(self.btn_browse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_8.addWidget(self.frame_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem11)
        self.btn_preview = QtWidgets.QPushButton(form_image_processing)
        self.btn_preview.setEnabled(False)
        self.btn_preview.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_preview.setObjectName("btn_preview")
        self.horizontalLayout_2.addWidget(self.btn_preview)
        self.btn_save = QtWidgets.QPushButton(form_image_processing)
        self.btn_save.setEnabled(False)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_back = QtWidgets.QPushButton(form_image_processing)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout_2.addWidget(self.btn_back)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem12)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(form_image_processing)
        QtCore.QMetaObject.connectSlotsByName(form_image_processing)

    def retranslateUi(self, form_image_processing):
        _translate = QtCore.QCoreApplication.translate
        form_image_processing.setWindowTitle(_translate("form_image_processing", "ImageProcessing"))
        self.cb_cvt_color.setText(_translate("form_image_processing", "Convert Color"))
        self.rb_gray.setText(_translate("form_image_processing", "Gray"))
        self.rb_color.setText(_translate("form_image_processing", "Color"))
        self.cb_resize.setText(_translate("form_image_processing", "Resize"))
        self.label_3.setText(_translate("form_image_processing", "Height"))
        self.label_2.setText(_translate("form_image_processing", "Width:"))
        self.cb_filters.setText(_translate("form_image_processing", "Filters"))
        self.cb_mean.setText(_translate("form_image_processing", "Mean"))
        self.cb_gaussian.setText(_translate("form_image_processing", "Gaussian"))
        self.cb_median.setText(_translate("form_image_processing", "Median"))
        self.cb_bilateral.setText(_translate("form_image_processing", "Bilateral"))
        self.cb_averaging.setText(_translate("form_image_processing", "Averaging"))
        self.cb_edges.setText(_translate("form_image_processing", "Edges"))
        self.rb_canny.setText(_translate("form_image_processing", "Canny"))
        self.rb_sobel.setText(_translate("form_image_processing", "Sobel"))
        self.rb_prewitt.setText(_translate("form_image_processing", "Prewitt"))
        self.rb_laplace.setText(_translate("form_image_processing", "Laplace"))
        self.cb_thresholding.setText(_translate("form_image_processing", "Thresholding"))
        self.rb_simple.setText(_translate("form_image_processing", "Simple"))
        self.rb_adaptive.setText(_translate("form_image_processing", "Adaptive"))
        self.rb_otsu.setText(_translate("form_image_processing", "OTSU"))
        self.cb_transformation.setText(_translate("form_image_processing", "Transformation"))
        self.cb_translation.setText(_translate("form_image_processing", "Translation"))
        self.lbl_posY.setText(_translate("form_image_processing", "PosY"))
        self.cb_perspective.setText(_translate("form_image_processing", "Perspective"))
        self.lbl_angle.setText(_translate("form_image_processing", "Angle:"))
        self.cb_rotation.setText(_translate("form_image_processing", "Rotation"))
        self.lbl_posX.setText(_translate("form_image_processing", "PosX"))
        self.lbl_image_path.setText(_translate("form_image_processing", "File Path : "))
        self.btn_browse.setText(_translate("form_image_processing", "Browse"))
        self.btn_preview.setText(_translate("form_image_processing", "Preview"))
        self.btn_save.setText(_translate("form_image_processing", "Save"))
        self.btn_back.setText(_translate("form_image_processing", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_image_processing = QtWidgets.QWidget()
    ui = Ui_form_image_processing()
    ui.setupUi(form_image_processing)
    form_image_processing.show()
    sys.exit(app.exec_())
