# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoInput_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form_video_input(object):
    def setupUi(self, form_video_input):
        form_video_input.setObjectName("form_video_input")
        form_video_input.resize(400, 300)
        form_video_input.setStyleSheet("QWidget{\n"
"background-color: rgb(75, 75, 75);\n"
"}\n"
"QComboBox{\n"
"background-color:rgb(50,50,50);\n"
"color:rgb(200,200,200)\n"
"}\n"
"QTreeView{\n"
"background-color:rgb(50,50,50);\n"
"border:1px solid rgb(25,25,25);\n"
"color:rgb(200,200,200)\n"
"}\n"
"QListView{\n"
"background-color:rgb(50,50,50);\n"
"border:1px solid rgb(25,25,25);\n"
"color:rgb(200,200,200)\n"
"}\n"
"QLineEdit{\n"
"color:rgb(200,200,200);\n"
"border:1px solid rgb(120,120,120);\n"
"background:rgb(50,50,50);\n"
"}\n"
"QPushButton {\n"
"  padding: 0px 8px;\n"
"  font-size: 16px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  outline: none;\n"
"  color: rgb(86,86,86);\n"
"  background-color: rgb(14,215,185);\n"
"  border: none;\n"
"  border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {background-color:  rgb(0,172,142);}\n"
"\n"
"QPushButton:hover:pressed {\n"
"  background-color: rgb(30,152,122);\n"
"}\n"
"QScrollBar:vertical {\n"
"    border:0px solid;\n"
"    background: rgb(50,50,50);\n"
"    width: 30px;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border:0px solid;\n"
"    background: rgb(50,50,50);\n"
"    height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: rgb(80,80,80);\n"
"    width:10px;\n"
"    margin:10px;\n"
"    border-radius:5px;\n"
"    min-height:30px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(80,80,80);\n"
"    height:10px;\n"
"    margin:10px;\n"
"    border-radius:5px;\n"
"    min-width:30px;\n"
"}\n"
"QScrollBar::add-page, QScrollBar::sub-page{\n"
"background:none;\n"
"}\n"
"QScrollBar::add-page:vertical{\n"
"width:0px;\n"
"}\n"
"QScrollBar::sub-page:vertical{\n"
"width:0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"width: 0px;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"width: 0px;\n"
"}\n"
"QScrollBar::add-page:horizontal{\n"
"height:0px;\n"
"}\n"
"QScrollBar::sub-page:horizontal{\n"
"height:0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"height: 0px;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"height: 0px;\n"
"}\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    width:0px;\n"
" }\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    height:0px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(form_video_input)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(44, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(form_video_input)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.le_video_path = QtWidgets.QLineEdit(form_video_input)
        self.le_video_path.setMinimumSize(QtCore.QSize(300, 0))
        self.le_video_path.setObjectName("le_video_path")
        self.horizontalLayout_2.addWidget(self.le_video_path)
        self.btn_browse = QtWidgets.QPushButton(form_video_input)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout_2.addWidget(self.btn_browse)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_next = QtWidgets.QPushButton(form_video_input)
        self.btn_next.setObjectName("btn_next")
        self.horizontalLayout.addWidget(self.btn_next)
        self.btn_back = QtWidgets.QPushButton(form_video_input)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(43, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)

        self.retranslateUi(form_video_input)
        QtCore.QMetaObject.connectSlotsByName(form_video_input)

    def retranslateUi(self, form_video_input):
        _translate = QtCore.QCoreApplication.translate
        form_video_input.setWindowTitle(_translate("form_video_input", "Video Input"))
        self.label.setText(_translate("form_video_input", "Select Video File"))
        self.btn_browse.setText(_translate("form_video_input", "Browse"))
        self.btn_next.setText(_translate("form_video_input", "Next"))
        self.btn_back.setText(_translate("form_video_input", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    form_video_input = QtWidgets.QWidget()
    ui = Ui_form_video_input()
    ui.setupUi(form_video_input)
    form_video_input.show()
    sys.exit(app.exec_())
